"""
models/trainee.py
------------------
Defines the `Trainee` table - the CORE of this entire application.
Every trainee you train gets exactly one row here.

This file also demonstrates THREE LAYERS of validation working together
(a real-world best practice called "defense in depth"):

    1. DATABASE-LEVEL constraints (unique=, nullable=, CheckConstraint)
       -> enforced by SQLite itself, the last line of defense. Even if
          buggy Python code tries to sneak in bad data, the database
          will refuse it.
    2. ORM-LEVEL validation (@validates decorator below)
       -> catches mistakes the moment a Python object's field is set,
          before we even try to save it. Gives us nicer Python error
          messages instead of a raw database error.
    3. FORM-LEVEL validation (Flask-WTF, built in Milestone 5)
       -> catches mistakes at the browser/form stage and shows the user
          a friendly message ("Mobile number must be 10 digits") instead
          of a crash.

We only build layers 1 and 2 in this milestone. Layer 3 comes later when
we build the Add Trainee form.
"""

import re
from datetime import datetime
from sqlalchemy.orm import validates
from models import db


class Trainee(db.Model):
    """
    Represents one person who has gone through the cybersecurity
    awareness training program.

    Table name (auto-generated by SQLAlchemy): 'trainee'
    """

    # --------------------------------------------------------------
    # PRIMARY KEY
    # --------------------------------------------------------------
    id = db.Column(db.Integer, primary_key=True)

    # --------------------------------------------------------------
    # PERSONAL DETAILS
    # --------------------------------------------------------------
    # nullable=False on all of these means the database will REFUSE to
    # save a Trainee row if any of these fields are missing - even if
    # our Python/form validation somehow gets bypassed.
    full_name = db.Column(db.String(100), nullable=False)

    # We restrict gender to a small fixed set of values. A CheckConstraint
    # is a rule the DATABASE enforces on every insert/update - here it
    # says "gender must be one of these 3 exact strings, no typos allowed."
    gender = db.Column(db.String(10), nullable=False)

    age = db.Column(db.Integer, nullable=False)

    # --------------------------------------------------------------
    # CONTACT / IDENTITY
    # --------------------------------------------------------------
    # unique=True -> the database will REJECT a second trainee row with
    # a mobile number that already exists. This directly implements the
    # assignment's "prevent duplicate mobile numbers" requirement at the
    # strongest possible level (the database itself), not just in our
    # Python code.
    mobile_number = db.Column(db.String(10), unique=True, nullable=False)

    aadhaar_number = db.Column(db.String(12), nullable=False)

    # Same idea as mobile_number: reference_id (the certificate reference
    # issued by WNS) must never be duplicated across trainees.
    reference_id = db.Column(db.String(50), unique=True, nullable=False)

    # --------------------------------------------------------------
    # TRAINING DETAILS
    # --------------------------------------------------------------
    training_date = db.Column(db.Date, nullable=False)

    # --------------------------------------------------------------
    # UPLOADED FILES
    # --------------------------------------------------------------
    # IMPORTANT DESIGN DECISION: we do NOT store the actual certificate
    # bytes inside the database. Databases are slow and bloated when
    # storing large binary files. Instead, we save the physical file to
    # disk (uploads/certificates/, built in
    # Milestone 6) and store only the FILENAME here as a string pointer.
    # This is the standard, scalable approach used in real applications.
    #
    # nullable=True because a trainee record can be created first, with
    # the certificate uploaded a little later - we shouldn't force it
    # to exist at the exact same moment.
    certificate_filename = db.Column(db.String(255), nullable=True)

    # --------------------------------------------------------------
    # METADATA
    # --------------------------------------------------------------
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    # --------------------------------------------------------------
    # TABLE-LEVEL CONSTRAINTS
    # --------------------------------------------------------------
    # __table_args__ lets us add constraints that involve rules rather
    # than a single column. CheckConstraint runs INSIDE SQLite on every
    # insert/update - if the condition is False, SQLite raises an error
    # and refuses to save the row.
    __table_args__ = (
        db.CheckConstraint(
            "gender IN ('Male', 'Female', 'Other')",
            name="ck_trainee_gender_valid",
        ),
        db.CheckConstraint(
            "age >= 1 AND age <= 120",
            name="ck_trainee_age_reasonable",
        ),
        db.CheckConstraint(
            "length(mobile_number) = 10",
            name="ck_trainee_mobile_length",
        ),
        db.CheckConstraint(
            "length(aadhaar_number) = 12",
            name="ck_trainee_aadhaar_length",
        ),
    )

    # --------------------------------------------------------------
    # ORM-LEVEL VALIDATION (runs in Python, before hitting the database)
    # --------------------------------------------------------------
    # The @validates decorator tells SQLAlchemy: "every time someone
    # sets trainee.mobile_number = something, run this function first."
    # It's a great early checkpoint - it catches mistakes with a clear
    # Python error message rather than a cryptic SQLite error.
    @validates("mobile_number")
    def validate_mobile_number(self, key, value):
        if not re.fullmatch(r"\d{10}", value or ""):
            raise ValueError("Mobile number must be exactly 10 digits.")
        return value

    @validates("aadhaar_number")
    def validate_aadhaar_number(self, key, value):
        if not re.fullmatch(r"\d{12}", value or ""):
            raise ValueError("Aadhaar number must be exactly 12 digits.")
        return value

    @validates("gender")
    def validate_gender(self, key, value):
        allowed = {"Male", "Female", "Other"}
        if value not in allowed:
            raise ValueError(f"Gender must be one of {allowed}.")
        return value

    @validates("full_name", "reference_id")
    def validate_not_blank(self, key, value):
        # A common real bug: someone submits a form with just spaces
        # (" ") in a required text field. .strip() removes leading/
        # trailing whitespace so we can catch that case too.
        if not value or not value.strip():
            raise ValueError(f"{key.replace('_', ' ').title()} cannot be blank.")
        return value

    def __repr__(self):
        return f"<Trainee id={self.id} name={self.full_name} ref={self.reference_id}>"

    # --------------------------------------------------------------
    # VERSION 1.0: DISPLAY HELPER (not a database column)
    # --------------------------------------------------------------
    @property
    def masked_aadhaar(self):
        """
        Returns this trainee's Aadhaar number masked for on-screen
        display (e.g. "XXXX XXXX 9012"). This is a Python @property,
        NOT a database column - it computes the masked value on the
        fly from the real aadhaar_number every time it's accessed, so
        there's zero risk of it drifting out of sync and zero schema
        change involved. See utils/security.py for the masking logic.
        """
        from utils.security import mask_aadhaar
        return mask_aadhaar(self.aadhaar_number)
