"""
models/user.py
---------------
Defines the `User` table - this represents the ADMIN account that logs
into the portal. The assignment only needs ONE admin account, but we
still model it as a proper table (not a hardcoded username/password in
code) because that's how real applications are built, and it sets us up
cleanly for Flask-Login in Milestone 3.

WHAT IS db.Model?
-------------------
`db.Model` is a special base class from Flask-SQLAlchemy. When our
`User` class inherits from it, SQLAlchemy automatically knows:
    - This class represents a database TABLE
    - Each class attribute (id, username, ...) represents a COLUMN
    - Each User object we create represents a ROW in that table

This is called an ORM - Object Relational Mapper. It lets us write
Python code like `User(username="admin")` instead of raw SQL like
`INSERT INTO user (username) VALUES ('admin')`. Both do the same thing
underneath, but the ORM version is safer (protects against SQL
injection automatically) and easier to read/maintain.
"""

from datetime import datetime
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from models import db


class User(db.Model, UserMixin):
    """
    Represents the admin account.

    Table name (auto-generated by SQLAlchemy from the class name):
        'user'

    MILESTONE 3 UPDATE: this class now also inherits from `UserMixin`
    (provided by Flask-Login). This does NOT add any new database
    columns or change the schema from Milestone 2 in any way - it
    purely adds four small Python methods/properties that Flask-Login
    requires to manage a "logged in user":
        - is_authenticated  -> True if the user has valid login credentials
        - is_active         -> True unless we've deactivated the account
        - is_anonymous      -> False (this is a real user, not a guest)
        - get_id()          -> returns self.id as a string, used to store
                                 the user's identity in the session cookie
    UserMixin provides sensible default implementations of all four, so
    we don't have to write them ourselves.
    """

    # --------------------------------------------------------------
    # id: PRIMARY KEY
    # --------------------------------------------------------------
    # Every table needs a way to uniquely identify each row. `primary_key=True`
    # tells SQLite to auto-increment this number (1, 2, 3, ...) every time
    # a new row is inserted. We will only ever have 1 row here, but every
    # well-designed table has a primary key regardless.
    id = db.Column(db.Integer, primary_key=True)

    # --------------------------------------------------------------
    # username
    # --------------------------------------------------------------
    # unique=True   -> SQLite will REJECT any attempt to insert a second
    #                  user with the same username. This is enforced at
    #                  the DATABASE level, not just in our Python code -
    #                  a strong safety net.
    # nullable=False -> this field is REQUIRED. You cannot save a User
    #                  without a username.
    username = db.Column(db.String(50), unique=True, nullable=False)

    # --------------------------------------------------------------
    # password_hash
    # --------------------------------------------------------------
    # CRITICAL SECURITY RULE: we NEVER store the actual plain-text
    # password anywhere in the database. Instead, in Milestone 3 we will
    # use Werkzeug's generate_password_hash() to scramble the password
    # into a long irreversible string, and store THAT here. When the
    # admin logs in, we hash whatever they type and compare the hashes -
    # we never need to "unscramble" the stored one.
    # String(255) gives enough room for modern hash algorithms (scrypt
    # hashes can be 100+ characters).
    password_hash = db.Column(db.String(255), nullable=False)

    # --------------------------------------------------------------
    # created_at
    # --------------------------------------------------------------
    # default=datetime.utcnow means: "if the code creating this row
    # doesn't explicitly set created_at, automatically fill it in with
    # the current date/time." Note we pass the FUNCTION `datetime.utcnow`
    # (no parentheses) - SQLAlchemy calls it itself at insert time. If we
    # wrote `datetime.utcnow()` here, it would be evaluated ONCE when the
    # app starts, and every row would get the same frozen timestamp - a
    # very common beginner bug.
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        """
        __repr__ controls what you see when you print a User object or
        inspect it in the Python shell, e.g. print(user) or just typing
        `user` in the interactive shell. Purely a debugging convenience -
        has no effect on the database or the app's behavior.
        """
        return f"<User id={self.id} username={self.username}>"

    # ------------------------------------------------------------------
    # PASSWORD HASHING (Milestone 3)
    # ------------------------------------------------------------------
    # WHY WE HASH PASSWORDS INSTEAD OF STORING THEM DIRECTLY:
    # If our database were ever leaked or stolen (via a bug, a backup
    # left somewhere unsafe, an SQL injection, etc.), plain-text
    # passwords would immediately compromise every admin account - and
    # since people often reuse passwords, potentially other accounts
    # too. A HASH is a one-way mathematical transformation: it's easy to
    # turn "admin123" into a scrambled string, but computationally
    # infeasible to reverse the scrambled string back into "admin123".
    # So even if the database leaks, the real password stays unknown.
    def set_password(self, plain_text_password):
        """
        Hashes the given plain-text password and stores the hash in
        self.password_hash. Called when creating the admin account or
        if we ever add a "change password" feature.

        generate_password_hash() from Werkzeug automatically:
          1. Picks a strong modern algorithm (scrypt by default).
          2. Generates a random "salt" (extra random data mixed into the
             hash) so that two identical passwords never produce the
             same stored hash - this defeats precomputed "rainbow table"
             attacks.
          3. Returns everything (algorithm + salt + hash) packed into
             one string, ready to store directly in password_hash.
        """
        self.password_hash = generate_password_hash(plain_text_password)

    def check_password(self, plain_text_password):
        """
        Used during login. Takes whatever the user just typed into the
        password field, hashes it using the SAME algorithm+salt stored
        in password_hash, and compares the two hashes.

        We never "decrypt" password_hash - that's not even possible.
        We just check "does hashing this new input produce the same
        result as what we stored?" Returns True/False.
        """
        return check_password_hash(self.password_hash, plain_text_password)

    # ------------------------------------------------------------------
    # DEFAULT ADMIN CREATION (Milestone 3)
    # ------------------------------------------------------------------
    @classmethod
    def create_default_admin_if_missing(cls):
        """
        Ensures exactly ONE admin account exists in the database.

        HOW IT WORKS:
        1. Query the `user` table for anyone with username="admin".
        2. If that query finds NOTHING (`is None`), we know this is the
           very first time the app has ever been run - so we create the
           account: username "admin", password "admin123" (hashed
           immediately via set_password - the plain text is NEVER
           written to the database).
        3. If the query DOES find an existing admin, we do absolutely
           nothing and leave that row untouched. This is what makes it
           safe to call this function every single time the app starts
           (see app.py) - it will never create duplicate admins or
           silently reset your password back to "admin123" after
           you've changed it in Settings later on.

        This classmethod is called once, inside an app context, right
        after db.create_all() in app.py.
        """
        existing_admin = cls.query.filter_by(username="admin").first()
        if existing_admin is None:
            admin = cls(username="admin")
            admin.set_password("admin123")
            db.session.add(admin)
            db.session.commit()
            print("[INFO] Default admin account created (username: admin / password: admin123)")
            print("[INFO] Please change this password from Settings after your first login.")

